### ISSUE TITLE
Please bump version 0.3.7!

### ISSUE THREAD

**Issue by naumenko-sa** [brentp/geneimpacts#17]
Hi @brentp !

Could you please create a new release of geneimpacts?
Otherwise the change https://github.com/brentp/geneimpacts/pull/16
is not propagated to bioconda/bcbio and ensembl_gene_id is empty in gemini.db
after bcbio upgrade.

Thanks!
Sergey

**Comment by brentp** [comment]
how is this related to #16 ?

**Comment by naumenko-sa** [comment]
The last release of geneimpacts was in June 2018 https://github.com/brentp/geneimpacts/releases/tag/v0.3.6
#16 was added in September 2018 after the v.0.3.6 release
bcbio_1.1.5 installs geneimpacts 0.3.6 without that change and the bug is still there in the fresh installation:
https://github.com/quinlan-lab/vcf2db/issues/48

SN

**Comment by brentp** [comment]
done. thank you.
