### ISSUE TITLE
Bump splice_region_variant to MED

### ISSUE THREAD

**Issue by arq5x** [brentp/geneimpacts#5]
In the interest of reducing false negatives.

**Comment by brentp** [comment]
so this would mean that a splice_region_variant would have higher impact than a synonymous variant and therefore that a non-coding change has a higher impact than a coding change.
OK?

**Comment by arq5x** [comment]
In the context of rare disease research, yeah I think this makes sense, though one could make arguments in either direction.
On January 25, 2016 at 8:37:17 AM, Brent Pedersen - Bioinformatics (notifications@github.com) wrote:

so this would mean that a splice_region_variant would have higher impact than a synonymous variant and therefore that a non-coding change has a higher impact than a coding change.
OK?
